---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  serviceSubnet: "10.43.240.0/24"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "storage=enabled"
    extraMounts:
      - hostPath: /tmp
        containerPath: /storage
        readOnly: true
        propagation: HostToContainer
