---
nameOverride: ""
fullnameOverride: ""

rsync:
  sourcePath: /mnt/nas
  targetPath: /mnt/nas-backup
  args: -av --delete
  cron: "*/15 * * * *"

replicaCount: 1
image:
  repository: ghcr.io/two-tauers/rsync
  pullPolicy: IfNotPresent
  imagePullSecrets: []
  tag: 2.4

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000 # should match linux GID

containerSecurityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
