---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nfsProvisioner.rbac.accountName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.nfsProvisioner.rbac.accountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.nfsProvisioner.rbac.accountName }}
  apiGroup: rbac.authorization.k8s.io
