---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "samba.selectorLabels" . | nindent 4 }}
  ports:
    - port: 445
      name: tcp-445
