{{- if .Values.samba.userSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "samba.fullname" . }}-users
  labels:
    {{- include "samba.labels" . | nindent 4 }}
type: Opaque
data:
  {{ range $i, $s := .Values.samba.userSecret.users }}
  {{ $suffix := add1 $i }}
  USER{{$suffix}}: {{ printf "%s;%s" .username .password | b64enc | quote }}
  {{ end }}
{{- end -}}
