---
apiVersion: v2
name: prometheus-agents
description: A Helm chart for prometheus agent and promtail
type: application
version: 0.1.0
appVersion: ""

dependencies:
- name: "prometheus"
  condition: prometheus.enabled
  version: "~15.5.3"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^6.6.1"
