---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
data:
  filebrowser: |
    {
      "port": {{ .Values.service.targetPort }},
      "baseURL": "{{ .Values.ingress.baseURL }}",
      "address": "",
      "log": "stdout",
      "database": "/filebrowser-db/database.db",
      "root": "/srv"
    }
