---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.filebrowser.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
