---
{{- if .Values.ingress.enable }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: {{ .Values.ingress.baseURL }}
            backend:
              service:
                name: {{ include "filebrowser.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{ end }}
