{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflared.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.nodeSelector }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end -}}
