---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflared.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.nodeSelector }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 8 }}
data:
  config.yaml: |
    {{- toYaml .Values.cloudflared.config | nindent 4 }}
