---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflared.fullname" . }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.cloudflared.config | nindent 4 }}