---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      labels:
        {{- include "cloudflared.selectorLabels" . | nindent 12 }}
    spec:
      serviceAccountName: {{ include "cloudflared.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      restartPolicy: {{ .Values.image.restartPolicy }}
      containers:
        - name: cloudflared-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 16 }}
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          - name: tunnel-config
            mountPath: /etc/cloudflared/config
            readOnly: true
          - name: tunnel-credentials
            mountPath: /etc/cloudflared/creds
            readOnly: true
      volumes:
        - name: tunnel-credentials
          secret:
            secretName: {{ .Values.cloudflared.secret.name }}
        - name: tunnel-config
          configMap:
            name: {{ include "cloudflared.fullname" . }}
            items:
            - key: config.yaml
              path: config.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
