
name: Lint and Test

on: 
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.1
      - name: Helm lint
        run: |-
          CHART_DIRS="$(git diff --find-renames --name-only "$(git rev-parse --abbrev-ref HEAD)" remotes/origin/main -- charts | grep '[cC]hart.yaml' | sed -e 's#/[Cc]hart.yaml##g')"
          for CHART_DIR in ${CHART_DIRS}; do
            helm lint ${CHART_DIR}
          done

  schema-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.23.1
          - v1.24.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: |-
          CHART_DIRS="$(git diff --find-renames --name-only "$(git rev-parse --abbrev-ref HEAD)" remotes/origin/main -- charts | grep '[cC]hart.yaml' | sed -e 's#/[Cc]hart.yaml##g')"
          KUBEVAL_VERSION="v0.16.1"
          SCHEMA_LOCATION="https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/"

          # install kubeval
          echo -n "Downloading kubeval... "
          curl --silent --show-error --fail --location --output /tmp/kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/download/"${KUBEVAL_VERSION}"/kubeval-linux-amd64.tar.gz && echo "done" || "ERROR"
          echo -n "Unpacking kubeval... "
          tar -xf /tmp/kubeval.tar.gz kubeval && echo "done" || "ERROR"

          # validate charts
          # set "--ignore-missing-schemas" kubeval flag if you're using custom resource definitions
          for CHART_DIR in ${CHART_DIRS}; do
              echo && echo "Validating $CHART_DIR..."
              helm template "${CHART_DIR}" | ./kubeval --strict --kubernetes-version "${KUBERNETES_VERSION#v}" --schema-location "${SCHEMA_LOCATION}" && echo "Validated $CHART_DIR" || "ERROR VALIDATING $CHART_DIR"
          done

  install-test:
    needs:
      - lint
      - schema-validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.23.1@sha256:355a1e3b7b0fe315c896f63a73847c554aac8fb8615c6bf47f1ca303009e9a2d
          - v1.24.4@sha256:ba6a8a1bc35139cc0947a9269a6db577cf7a6ba37cab8088fd04142546dc0c21
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.1
      - name: Create KIND cluster
        uses: helm/kind-action@v1.3.0
        with:
          config: .github/kind.yaml
          node_image: "kindest/node:${{ matrix.k8s }}"
      - name: Install charts
        run: |-
          CHART_DIRS="$(git diff --find-renames --name-only "$(git rev-parse --abbrev-ref HEAD)" remotes/origin/main -- charts | grep '[cC]hart.yaml' | sed -e 's#/[Cc]hart.yaml##g')"
          for CHART_DIR in ${CHART_DIRS}; do
            dir=${CHART_DIR%*/}
            chart_name="${dir##*/}"
            if test -f $dir/setup.sh; then
              echo "Found $dir/setup.sh, running it..."
              bash $dir/setup.sh
            fi
            echo "Installing chart '$chart_name'"
            helm install $chart_name $dir && helm uninstall $chart_name 
          done
