
name: Lint and Test

on: 
  pull_request:
    paths:
      - 'charts/**'

env:
  CT_CONFIGFILE: .github/ct.yaml

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.2.1
        with:
          command: lint
          config: .github/ct.yaml
  kubeval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.22.0
          - v1.23.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: |-
          set -euo pipefail

          CHART_DIRS="$(git diff --find-renames --name-only "$(git rev-parse --abbrev-ref HEAD)" remotes/origin/main -- charts | grep '[cC]hart.yaml' | sed -e 's#/[Cc]hart.yaml##g')"
          KUBEVAL_VERSION="0.14.0"
          SCHEMA_LOCATION="https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/"

          # install kubeval
          curl --silent --show-error --fail --location --output /tmp/kubeval.tar.gz https://github.com/instrumenta/kubeval/releases/download/"${KUBEVAL_VERSION}"/kubeval-linux-amd64.tar.gz
          tar -xf /tmp/kubeval.tar.gz kubeval

          # validate charts
          for CHART_DIR in ${CHART_DIRS}; do
            helm template "${CHART_DIR}" | ./kubeval --strict --ignore-missing-schemas --kubernetes-version "${KUBERNETES_VERSION#v}" --schema-location "${SCHEMA_LOCATION}"
          done