---
name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup dependencies
        run: |-
          CHART_DIRS="$(find charts/*/Chart.yaml | sed -e 's#/[Cc]hart.yaml##g')"
          for CHART_DIR in ${CHART_DIRS}; do
            dir=${CHART_DIR%*/}
            chart_name="${dir##*/}"
            if test -f $dir/setup.sh; then
              echo "Found $dir/setup.sh, running it..."
              bash $dir/setup.sh
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
